# Generated by Django 3.0.5 on 2020-05-08 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200507_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
